[settings]
os=Linux
arch=armv6
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++11
build_type=Release
[options]
qt/*:opengl=es2
raspberry-pi-os/*:os=buster
[tool_requires]
cmake/3.23.5
raspberry-pi-os/0.0.9@com.github.tereius/stable
