name: "Build/Push Conan Docker Images"
on: push

jobs:
  build_conan_ubuntu_image:
    name: "Build/Push Ubuntu Docker Image"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to ghcr.io"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build/Push Docker Image"
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: docker/ubuntu
          platforms: linux/amd64
          push: true
          sbom: false
          provenance: false
          tags: |
            ghcr.io/privatehive/conan-ubuntu:latest
            ghcr.io/privatehive/conan-ubuntu:${{ github.ref_name }}

  build_conan_wine_image:
    name: "Build/Push Wine Docker Image"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to ghcr.io"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build/Push Docker Image"
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: docker/wine
          platforms: linux/amd64
          push: true
          sbom: false
          provenance: false
          tags: |
            ghcr.io/privatehive/conan-wine:latest
            ghcr.io/privatehive/conan-wine:${{ github.ref_name }}