name: "Upload Conan Recipe"
on:
  workflow_call:
    inputs:
      conan_recipe_path:
        required: false
        type: string
        default: "./"
      conan_upload_remote:
        required: false
        type: string
    secrets:
      conan_upload_password:
        required: false
      conan_upload_login:
        required: false

jobs:
  create:
    name: "Upload recipe"
    defaults:
      run:
        shell: bash -e {0}
    runs-on: self-hosted
    container:
      image: "ghcr.io/tereius/conan-ubuntu:latest"
    outputs:
      package_ref: ${{ steps.cache-package-ref.outputs.package_ref }}
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
      - name: "Clone conan workflow helper"
        uses: actions/checkout@v4
        with:
          repository: "Privatehive/conan-workflows"
          path: 'conan_workflow_helper'
          ref: 'master'
      - name: "Upload"
        run: /entrypoint.sh python ./conan_workflow_helper/.github/actions/upload.py
        env:
          CONAN_RECIPE_PATH: ${{ inputs.conan_recipe_path }}
          CONAN_UPLOAD: ${{ inputs.conan_upload_remote }}
          CONAN_PASSWORD: ${{ secrets.conan_upload_password }}
          CONAN_LOGIN_USERNAME: ${{ secrets.conan_upload_login }}
      - name: "Set package ref output"
        id: cache-package-ref
        run: echo "package_ref=$(cat conan_package_ref)" >> "$GITHUB_OUTPUT"
      - name: "Set repo property"
        run: "curl -L -X PATCH -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' https://api.github.com/repos/${{ github.repository }}/properties/values -d '{\"properties\": [{\"property_name\":\"conan-package\",\"value\":\"${{ steps.cache-package-ref.outputs.package_ref }}\"}]}'"

  #label:
  #  name: "Set repo property"
  #  needs: [create]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - run: "gh api --method PATCH -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' /repos/${{ github.repository }}/properties/values -f 'properties[][property_name]=conan-package' -f 'properties[][value]=${{ needs.create.outputs.package_ref }}'"
  #      env:
  #        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
